name: Deploy 1Panel using Official Installation Script

on:
  workflow_dispatch:  # 手动触发工作流

jobs:
  deploy:
    runs-on: ubuntu-22.04  # 使用 Ubuntu 22.04 作为运行环境

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        # 更新系统包
        sudo apt update
        sudo apt upgrade -y
        
        # 安装必要的工具和库
        sudo apt install -y curl wget sudo gnupg lsb-release ca-certificates tar

    - name: Run 1Panel installation script (non-interactive)
      run: |
        # 获取操作系统架构
        osCheck=`uname -a`
        if [[ $osCheck =~ 'x86_64' ]]; then
            architecture="amd64"
        elif [[ $osCheck =~ 'arm64' ]] || [[ $osCheck =~ 'aarch64' ]]; then
            architecture="arm64"
        elif [[ $osCheck =~ 'armv7l' ]]; then
            architecture="armv7"
        elif [[ $osCheck =~ 'ppc64le' ]]; then
            architecture="ppc64le"
        elif [[ $osCheck =~ 's390x' ]]; then
            architecture="s390x"
        else
            echo "暂不支持的系统架构，请参阅官方文档，选择受支持的系统。"
            exit 1
        fi

        # 设置安装模式为 stable（可以根据需要修改为 dev）
        INSTALL_MODE="stable"

        # 获取最新版本信息
        VERSION=$(curl -s https://resource.fit2cloud.com/1panel/package/${INSTALL_MODE}/latest)
        HASH_FILE_URL="https://resource.fit2cloud.com/1panel/package/${INSTALL_MODE}/${VERSION}/release/checksums.txt"

        if [[ "x${VERSION}" == "x" ]]; then
            echo "获取最新版本失败，请稍候重试"
            exit 1
        fi

        # 设置包文件和下载链接
        package_file_name="1panel-${VERSION}-linux-${architecture}.tar.gz"
        package_download_url="https://resource.fit2cloud.com/1panel/package/${INSTALL_MODE}/${VERSION}/release/${package_file_name}"
        expected_hash=$(curl -s "$HASH_FILE_URL" | grep "$package_file_name" | awk '{print $1}')

        # 如果文件已存在且哈希值一致，则跳过下载
        if [ -f ${package_file_name} ]; then
            actual_hash=$(sha256sum "$package_file_name" | awk '{print $1}')
            if [[ "$expected_hash" == "$actual_hash" ]]; then
                echo "安装包已存在，跳过下载"
                rm -rf 1panel-${VERSION}-linux-${architecture}
                tar zxvf ${package_file_name}
                cd 1panel-${VERSION}-linux-${architecture}
                /bin/bash install.sh
                exit 0
            else
                echo "已存在安装包，但是哈希值不一致，开始重新下载"
                rm -f ${package_file_name}
            fi
        fi

        echo "开始下载 1Panel ${VERSION} 版本在线安装包"
        echo "安装包下载地址： ${package_download_url}"

        curl -LOk -o ${package_file_name} ${package_download_url}
        curl -sfL https://resource.fit2cloud.com/installation-log.sh | sh -s 1p install ${VERSION}

        if [ ! -f ${package_file_name} ]; then
            echo "下载安装包失败，请稍候重试。"
            exit 1
        fi

        tar zxvf ${package_file_name}
        if [ $? != 0 ]; then
            echo "下载安装包失败，请稍候重试。"
            rm -f ${package_file_name}
            exit 1
        fi

        cd 1panel-${VERSION}-linux-${architecture}

        # 执行安装
        /bin/bash install.sh

    - name: Keep Action Running (Optional)
      run: sleep 3600  # 保持工作流运行 1 小时，以便访问 1Panel
