name: Build Imagebuilder with ssrp

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - rockchip
          #- mediatek_filogic

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib \
            gettext git libncurses-dev libssl-dev python3-pip rsync unzip zlib1g-dev
          sudo python3 -m pip install setuptools

      - name: Clone Lede source
        run: git clone --depth=1 https://github.com/coolsnowwolf/lede.git

      - name: Add helloworld feed (for luci-app-ssr-plus)
        run: |
          echo 'src-git helloworld https://github.com/fw876/helloworld.git' >> lede/feeds.conf.default

      - name: Update feeds
        run: |
          cd lede
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Setup config for ${{ matrix.platform }}
        run: |
          cd lede
          if [ "${{ matrix.platform }}" = "rockchip" ]; then
            echo "CONFIG_TARGET_rockchip=y" > .config
            echo "CONFIG_TARGET_rockchip_armv8=y" >> .config
            echo "CONFIG_TARGET_rockchip_armv8_DEVICE_radxa_e20c=y" >> .config
            echo "CONFIG_IB=y" >> .config
            echo "CONFIG_PACKAGE_luci-app-ssr-plus=m" >> .config
          elif [ "${{ matrix.platform }}" = "mediatek_filogic" ]; then
            echo "CONFIG_TARGET_mediatek=y" > .config
            echo "CONFIG_TARGET_mediatek_filogic=y" >> .config
            echo "CONFIG_TARGET_mediatek_filogic_DEVICE_glinet_gl-mt3000=y" >> .config
            echo "CONFIG_IB=y" >> .config
            echo "CONFIG_PACKAGE_luci-app-ssr-plus=m" >> .config
          fi
          make defconfig

      - name: Build ImageBuilder for ${{ matrix.platform }}
        run: |
          cd lede
          make -j$(nproc)

      - name: Upload ImageBuilder ${{ matrix.platform }}
        uses: actions/upload-artifact@v4
        with:
          name: imagebuilder-${{ matrix.platform }}
          path: lede/bin/targets/**/lede-imagebuilder-*.tar.*
