name: Deploy gh

on:
  workflow_dispatch:  # 手动触发工作流

jobs:
  deploy:
    runs-on: ubuntu-22.04  # 使用已预装 Docker 的 Ubuntu 22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run Halo Docker container
      run: |
        docker run -d --name="gh-proxy-py" \
          -p 0.0.0.0:8090:80 \
          --restart=always \
          hunsh/gh-proxy-py:latest

    - name: Install ngrok
      run: |
        curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc > /dev/null
        echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list > /dev/null
        sudo apt update
        sudo apt install -y ngrok

    - name: Login to ngrok
      run: |
        ngrok config add-authtoken 2qVQLubYiKrvHPPOR5gtsUFo8kU_33sC4hyV6febEuRF1Nfxs

    - name: Expose Halo with ngrok HTTP
      run: |
        ngrok http 8090 > /dev/null &
        sleep 5
        echo "Halo public URL:"
        curl -s http://127.0.0.1:4040/api/tunnels | jq '.tunnels[] | select(.proto=="https") | .public_url'

    - name: Keep Action Running
      run: sleep 7200  
