name: Deploy gh

on:
  workflow_dispatch:  # 手动触发工作流

jobs:
  deploy:
    runs-on: ubuntu-22.04  # 使用已预装 Docker 的 Ubuntu 22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create reverse-proxy.conf
      run: |
        cat <<'EOF' > reverse-proxy.conf
        server {
            listen 80;
            server_name localhost;

            location / {
                proxy_pass https://hub.docker.com;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_ssl_verify off;
            }
        }
        EOF
        cat reverse-proxy.conf

    - name: Check if reverse-proxy.conf is correctly mounted
      run: |
        docker exec nginx-proxy cat /etc/nginx/conf.d/reverse-proxy.conf

    - name: Remove default nginx config (if necessary)
      run: |
        docker exec nginx-proxy rm /etc/nginx/conf.d/default.conf

    - name: Run nginx-proxy Docker container
      run: |
        docker run -d \
            --name nginx-proxy \
            -p 8080:80 \
            -v $(pwd)/reverse-proxy.conf:/etc/nginx/conf.d/reverse-proxy.conf \
            nginx:latest
    
    - name: Check running containers
      run: docker ps

    - name: Debug nginx configuration
      run: |
        docker exec nginx-proxy nginx -T  # 查看所有加载的配置

    - name: Debug nginx logs
      run: |
        docker logs nginx-proxy

    - name: Install ngrok
      run: |
        curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc > /dev/null
        echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list > /dev/null
        sudo apt update
        sudo apt install -y ngrok

    - name: Login to ngrok
      run: |
        ngrok config add-authtoken 2qZR0FVfkTlsvBgZEMekdCGyxzE_6mYLLzLoQ9cPQ6sFyj7E6

    - name: Expose Halo with ngrok HTTP
      run: |
        ngrok http 8080 > /dev/null &
        sleep 5
        echo "Halo public URL:"
        curl -s http://127.0.0.1:4040/api/tunnels | jq '.tunnels[] | select(.proto=="https") | .public_url'

    - name: Keep Action Running
      run: sleep 21600
