name: 获取x86-64平台的docker镜像

on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: '请填写docker镜像名称，多个用英文逗号分开'
        required: true
        default: 'alpine:latest,alpine/curl'  # 修改默认镜像列表

jobs:
  pull_and_package:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 拉取所有docker镜像并压缩
        run: |
          images="${{ github.event.inputs.docker_images }}"
          IFS=',' read -r -a image_array <<< "$images"
          for image in "${image_array[@]}"; do
            # 拉取镜像
            docker pull "${image}" --platform "linux/amd64"
            # 保存为 .tar 文件，替换 / 和 : 为 _，避免文件路径问题
            image_name="${image//\//_}"  # 将 / 替换为 _
            image_name="${image_name//:/_}"  # 将 : 替换为 _
            docker save "${image}" -o "${image_name}-amd64.tar"
            # 压缩为 .tar.gz 文件
            tar -czf "${image_name}.tar.gz" "${image_name}-amd64.tar"
          done

      - name: 即将要发布到release的docker镜像列表
        run: |
          echo "Current working directory:"
          pwd
          echo "Listing .tar.gz files:"
          find $GITHUB_WORKSPACE -name "*.tar.gz"

      - name: 创建 GitHub Release
        uses: softprops/action-gh-release@master
        with:
          tag_name: x86-64-docker-images
          name: x86-64平台docker镜像如下
          body: 你可以使用加速站点下载release中的文件比如 https://ghp.ml1.one
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 准备即将要发布的文件列表
        id: set_files
        run: |
          # 查找所有 .tar.gz 文件并输出到环境变量中
          files=$(find $GITHUB_WORKSPACE -name "*.tar.gz")
          echo "Found files: $files"
          
          # 将每个文件路径按行写入环境变量
          for file in $files; do
            echo "FILES=$file" >> $GITHUB_ENV
          done

      - name: 上传所有docker镜像到release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: x86-64-docker-images
          files: ${{ env.FILES }}
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 清理临时文件
        run: rm *-amd64.tar
