name: Build ssrp

on:
  workflow_dispatch:
    inputs:
      openwrt_package:
        description: '请输入 OpenWrt 的包版本（如 packages-24.10）'
        required: true
        default: 'packages-24.10'  # 默认值，用户可以手动输入其他值

jobs:
  build:
    runs-on: ubuntu-22.04  # 设置为 Ubuntu 22.04
    env:
      OPENWRT_PACKAGE: ${{ github.event.inputs.openwrt_package }}  # 使用用户输入的包版本

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clone makeself repo
        run: |
          git clone https://github.com/megastep/makeself.git

      - name: Create directories for x86_64 and a53
        run: |
          mkdir -p x86_64/depends a53/depends

      - name: Download ipk files for x86_64 and a53
        run: |
          FILE_PREFIXES=("dns2tcp" "lua-neturl" "chinadns-ng" "dns2socks" "hysteria" "ipt2socks" "microsocks" "mosdns" "naiveproxy" "redsocks2" "shadowsocksr-libev" "shadowsocks-rust" "shadow-tls" "simple-obfs-client" "tcping" "trojan" "tuic-client" "v2ray-plugin" "xray-core" "luci-app-ssr-plus")
          BASE_URL="https://dl.openwrt.ai/${{ env.OPENWRT_PACKAGE }}/"

          # 使用 wget 获取目录页面并查找文件
          wget -qO- "$BASE_URL" | \
          while read -r LINE; do
              for PREFIX in "${FILE_PREFIXES[@]}"; do
                  # 使用 grep 检查文件名是否匹配
                  if [[ "$LINE" == *"$PREFIX"* ]]; then
                      # 提取 href 中的文件名部分
                      FILE=$(echo "$LINE" | grep -oP 'href="\K[^"]*')
                      
                      # 生成完整的文件 URL
                      FILE_URL="${BASE_URL}${FILE}"
                      
                      # 打印找到的文件 URL
                      echo "Found file: $FILE_URL"
                      
                      # 根据文件前缀判断文件存放路径
                      if [[ "$PREFIX" == "luci-app-ssr-plus" ]]; then
                          # 对于 luci-app-ssr-plus 文件，保存在 x86_64 和 a53 目录
                          wget "$FILE_URL" -P x86_64/
                          wget "$FILE_URL" -P a53/
                      else
                          # 其他文件保存在 depends 目录
                          wget "$FILE_URL" -P x86_64/depends/
                          wget "$FILE_URL" -P a53/depends/
                      fi
                  fi
              done
          done

  
      - name: Copy install.sh to a53
        run: |
          ls -lh x86_64
          ls -lh a53

   