name: SSH and Halo Deployment

on:
  workflow_dispatch: # 手动触发

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run Halo Server
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk wget
        wget -q https://github.com/halo-dev/halo/releases/latest/download/halo-2.7.3.jar -O halo.jar
        nohup java -jar halo.jar --server.port=8090 > halo.log 2>&1 &

    - name: Install and Configure SSH
      run: |
        sudo apt-get update
        sudo apt-get install -y openssh-server
        sudo service ssh start
        echo 'root:password' | sudo chpasswd # 修改 root 密码为 "password"
        sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
        sudo service ssh restart

    - name: Install ngrok
      run: |
        curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc > /dev/null
        echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list > /dev/null
        sudo apt update
        sudo apt install -y ngrok

    - name: Login to ngrok
      run: |
        ngrok config add-authtoken 2qVHcdtl1O216lq18DfIKbEDf93_7RWJLoanfALo28D711aHB

    - name: Expose SSH and Halo with ngrok
      run: |
        ngrok tcp 22 > /dev/null &
        ngrok http 8090 > /dev/null &
        sleep 5
        echo "Halo public URL:"
        curl -s http://127.0.0.1:4040/api/tunnels | jq '.tunnels[] | select(.proto=="https") | .public_url'
        echo "SSH public URL:"
        curl -s http://127.0.0.1:4040/api/tunnels | jq '.tunnels[] | select(.proto=="tcp") | .public_url'

    - name: Keep Action Running
      run: sleep 3600 # 保持虚拟机运行 1 小时
